server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Optional: cache static assets
    location / {
           try_files $uri /index.html;
       }

       location ^~ /issue-forecast/ {
        alias /usr/share/nginx/html/issue-forecast/;
        index index.html;
        try_files $uri $uri/ issue-forecast/index.html;
    }



}
